services:
  db:
    container_name: db
    image: neo4j
    volumes:
      - ./data:/data
    restart: always
    environment:
      NEO4J_AUTH: neo4j/${DB_PASSWORD}
      TZ: America/Toronto
      VIRTUAL_HOST: ${ADMIN_HOST}
      LETSENCRYPT_HOST: ${ADMIN_HOST}
      VIRTUAL_PORT: 7474
      # NEO4J_dbms_connector_http_listen__address: 80
      # NEO4J_dbms_connector_http_advertised__address: 80
    network_mode: bridge
    # uncomment to allow browser access with http://localhost:7474
    ports:
     - 7474:7474
     - 7687:7687
  api:
    container_name: api
    build:
      context: .
      dockerfile_inline: |
        FROM python:alpine
        RUN apk add --no-cache tzdata
        ENV TZ America/Toronto
        RUN pip3 install python-dateutil flask gunicorn sh neo4j
    depends_on:
      - db
    links:
     - db:db
    restart: always
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      VIRTUAL_HOST: ${API_HOST}
      LETSENCRYPT_HOST: ${API_HOST}
    volumes:
      - ./api:/api
    working_dir: /api
    # entrypoint: gunicorn api:api -w 1 --threads 1 -b 0.0.0.0:80
    # uncomment entrypoint & ports to test locally with hot reload at http://localhost:
    entrypoint: python api.py
    ports:
      - 80:80
    network_mode: bridge
